AWSTemplateFormatVersion: 2010-09-09

Parameters:
  TemplateBucketName:
    Type: String
    Default: awstut-bucket
    
  Prefix:
    Type: String
    Default: soa-05-005

  InstanceImageId:
    Type: String
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-arm64
    
  InstanceType:
    Type: String
    Default: t4g.nano
    
  HTTPPort:
    Type: Number
    Default: 80

  LambdaArchitecture:
    Type: String
    Default: arm64
    
  LambdaHandler:
    Type: String
    Default: index.lambda_handler
    
  LambdaRuntime:
    Type: String
    Default: python3.12
    
  VXLANPort:
    Type: Number
    Default: 4789
    
    
Resources:
  VPCStack1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-vpc-01.yaml"
      Parameters:
        AvailabilityZone1: a
        AvailabilityZone2: d
        CidrIp1: 10.0.1.0/24
        CidrIp2: 10.0.2.0/24
        HTTPPort: !Ref HTTPPort
        Prefix: !Ref Prefix
        VPCCidrBlock: 10.0.0.0/16
        VXLANPort: !Ref VXLANPort

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack1
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-ec2.yaml"
      Parameters:
        ImageId: !Ref InstanceImageId
        InstanceSecurityGroup1: !GetAtt VPCStack1.Outputs.InstanceSecurityGroup1
        InstanceSecurityGroup2: !GetAtt VPCStack1.Outputs.InstanceSecurityGroup2
        InstanceType: !Ref InstanceType
        Prefix: !Ref Prefix
        PublicSubnet1: !GetAtt VPCStack1.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt VPCStack1.Outputs.PublicSubnet2

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - EC2Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-lambda.yaml"
      Parameters:
        Architecture: !Ref LambdaArchitecture
        Handler: !Ref LambdaHandler
        Prefix: !Ref Prefix
        Runtime: !Ref LambdaRuntime
        SourceInstance: !GetAtt EC2Stack.Outputs.SourceInstance
        TargetInstance: !GetAtt EC2Stack.Outputs.TargetInstance
        
  VPCStack2:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - LambdaStack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-vpc-02.yaml"
      Parameters:
        HTTPPort: !Ref HTTPPort
        SourceNetworkInterfaceId: !GetAtt LambdaStack.Outputs.SourceNetworkInterfaceId
        TargetNetworkInterfaceId: !GetAtt LambdaStack.Outputs.TargetNetworkInterfaceId
