AWSTemplateFormatVersion: 2010-09-09

Parameters:
  HTTPPort:
    Type: Number
    
  SourceNetworkInterfaceId:
    Type: String
  
  TargetNetworkInterfaceId:
    Type: String


Resources:
  TrafficMirrorFilter:
    Type: AWS::EC2::TrafficMirrorFilter
    Properties:
      NetworkServices: 
        - amazon-dns

  TrafficMirrorFilterRule:
    Type: AWS::EC2::TrafficMirrorFilterRule
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      DestinationPortRange: 
        FromPort: !Ref HTTPPort
        ToPort: !Ref HTTPPort
      Protocol: 6
      RuleAction: accept
      RuleNumber: 10
      SourceCidrBlock: 0.0.0.0/0
      SourcePortRange: 
        FromPort: 0
        ToPort: 65535
      TrafficDirection: ingress
      TrafficMirrorFilterId: !Ref TrafficMirrorFilter
    
  TrafficTarget:
    Type: AWS::EC2::TrafficMirrorTarget
    Properties:
      NetworkInterfaceId: !Ref TargetNetworkInterfaceId

  TrafficMirrorSession:
    Type: AWS::EC2::TrafficMirrorSession
    Properties:
      Description: String
      NetworkInterfaceId: !Ref SourceNetworkInterfaceId
      SessionNumber: 10
      TrafficMirrorFilterId: !Ref TrafficMirrorFilter
      TrafficMirrorTargetId: !Ref TrafficTarget
