AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>

  InstanceSecurityGroup1:
    Type: String
    
  InstanceSecurityGroup2:
    Type: String
    
  InstanceType:
    Type: String
    
  Prefix:
    Type: String

  PublicSubnet1:
    Type: String
    
  PublicSubnet2:
    Type: String
    
    
Resources:
  SourceInstance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref InstanceProfile
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - !Ref InstanceSecurityGroup1
          SubnetId: !Ref PublicSubnet1
      UserData: !Base64 |
        #!/bin/bash -xe
        dnf update -y
        dnf install -y httpd
        
        systemctl start httpd
        systemctl enable httpd
        ec2-metadata -i > /var/www/html/index.html
          
  TargetInstance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref InstanceProfile
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - !Ref InstanceSecurityGroup2
          SubnetId: !Ref PublicSubnet2
      UserData: !Base64
        Fn::Sub: |
          #!/bin/bash -xe
          dnf update -y
          dnf install -y tcpdump

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref InstanceRole
  
  InstanceRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Delete
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - ec2.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore


Outputs:
  SourceInstance:
    Value: !Ref SourceInstance

  TargetInstance:
    Value: !Ref TargetInstance
