AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Bucket:
    Type: String

  Prefix:
    Type: String


Resources:
  Document:
    Type: AWS::SSM::Document
    Properties: 
      Content:
        assumeRole: "{{AutomationAssumeRole}}"
        description: Run a script on Linux instances.
        schemaVersion: "0.3"
        parameters:
          AutomationAssumeRole:
            type: String
            description: (Optional) The ARN of the role that allows Automation to perform the actions on your behalf.
            default: ""
          InstanceId:
            type: String
            description: (Required) The instance ID you want to run commands on.
            default: ""
        mainSteps:
          - name: copy
            action: aws:runCommand
            inputs:
              DocumentName: AWS-RunShellScript
              InstanceIds:
                - "{{InstanceId}}"
              Parameters:
                commands:
                  - !Sub "sudo aws s3 cp /var/log/messages s3://${Bucket}/{{InstanceId}}/messages"
      DocumentFormat: YAML
      DocumentType: Automation
      Name: !Sub "${Prefix}-document"
      TargetType: /

  DocumentRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Delete
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - ssm.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonSSMAutomationRole

                  
Outputs:
  Document:
    Value: !Ref Document

  DocumentRoleArn:
    Value: !GetAtt DocumentRole.Arn
