AWSTemplateFormatVersion: 2010-09-09

Parameters:
  TemplateBucketName:
    Type: String
    Default: awstut-bucket
    
  Prefix:
    Type: String
    Default: soa-01-001

  SSEAlgorithm:
    Type: String
    Default: AES256
  

Resources:
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-s3.yaml"
      Parameters:
        Prefix: !Ref Prefix
        SSEAlgorithm: !Ref SSEAlgorithm

  ConfigStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - S3Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-config.yaml"
      Parameters:
        ConfigBucket: !GetAtt S3Stack.Outputs.ConfigBucket
        Prefix: !Ref Prefix
        SSEAlgorithm: !Ref SSEAlgorithm
        TestBucket: !GetAtt S3Stack.Outputs.TestBucket
