AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DLMTagKey:
    Type: String
    
  DLMTagAmiValue:
    Type: String
  
  DLMTagEbsValue:
    Type: String
  
  DLMTagInstanceValue:
    Type: String
    
  Prefix:
    Type: String
    
    
Resources:
  AMILifecyclePolicy:
    Type: AWS::DLM::LifecyclePolicy
    Properties: 
      Description: !Sub "${Prefix}-LifecyclePolicy-AMI"
      ExecutionRoleArn: !GetAtt AWSDataLifecycleManagerDefaultRoleForAMIManagement.Arn
      PolicyDetails: 
        Parameters: 
          NoReboot: false
        PolicyType: IMAGE_MANAGEMENT
        ResourceTypes: 
          - INSTANCE
        Schedules: 
          - CreateRule: 
              Interval: 1
              IntervalUnit: HOURS
            DeprecateRule: # AMI only.
              Count: 1
            Name: test-ami-policy
            RetainRule: 
              Count: 2
        TargetTags: 
          - Key: !Ref DLMTagKey
            Value: !Ref DLMTagAmiValue
      State: ENABLED
      
  EBSLifecyclePolicy:
    Type: AWS::DLM::LifecyclePolicy
    Properties: 
      Description: !Sub "${Prefix}-LifecyclePolicy-EBS"
      ExecutionRoleArn: !GetAtt AWSDataLifecycleManagerDefaultRole.Arn
      PolicyDetails: 
        PolicyType: EBS_SNAPSHOT_MANAGEMENT
        ResourceTypes: 
          - VOLUME
        Schedules: 
          - CreateRule: 
              Interval: 1
              IntervalUnit: HOURS
            Name: test-ami-policy
            RetainRule: 
              Count: 2
        TargetTags: 
          - Key: !Ref DLMTagKey
            Value: !Ref DLMTagEbsValue
      State: ENABLED
      
  InstanceLifecyclePolicy:
    Type: AWS::DLM::LifecyclePolicy
    Properties: 
      Description: !Sub "${Prefix}-LifecyclePolicy-Instance"
      ExecutionRoleArn: !GetAtt AWSDataLifecycleManagerDefaultRole.Arn
      PolicyDetails: 
        Parameters: 
          ExcludeBootVolume: false
        PolicyType: EBS_SNAPSHOT_MANAGEMENT
        ResourceTypes: 
          - INSTANCE
        Schedules: 
          - CreateRule: 
              Interval: 1
              IntervalUnit: HOURS
            Name: test-ami-policy
            RetainRule: 
              Count: 2
        TargetTags: 
          - Key: !Ref DLMTagKey
            Value: !Ref DLMTagInstanceValue
      State: ENABLED
        
  AWSDataLifecycleManagerDefaultRoleForAMIManagement:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - dlm.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSDataLifecycleManagerServiceRoleForAMIManagement
        
  AWSDataLifecycleManagerDefaultRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - dlm.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSDataLifecycleManagerServiceRole
