AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DLMTagAmiValue:
    Type: String
    
  DLMTagInstanceValue:
    Type: String
    
  DLMTagKey1:
    Type: String
    
  DLMTagKey2:
    Type: String

  ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>

  InstanceSubnet:
    Type: String

  InstanceType:
    Type: String
    
  Prefix:
    Type: String
    

Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref InstanceSubnet
      Tags:
        - Key: !Ref DLMTagKey1
          Value: !Ref DLMTagAmiValue
        - Key: !Ref DLMTagKey2
          Value: !Ref DLMTagInstanceValue
            
        
Outputs:
  Instance:
    Value: !Ref Instance
