AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>

  InstanceSubnet:
    Type: String

  InstanceType:
    Type: String
    
  Prefix:
    Type: String
    

Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref InstanceSubnet
      Tags:
        - Key: DLM
          Value: INSTANCE
        - Key: DLM
          Value: AMI
            
Outputs:
  Instance:
    Value: !Ref Instance
