AWSTemplateFormatVersion: 2010-09-09

Parameters:
  TemplateBucketName:
    Type: String
    Default: [bucket-name]
    
  Prefix:
    Type: String
    Default: soa-02-005

  TagKey:
    Type: String
    Default: DeleteImage
    
  TagValue:
    Type: String
    Default: true
    
  WaitForSuccessTimeoutSeconds:
    Type: Number
    Default: 600
    
  ValidHours:
    Type: Number
    Default: 1
    
Resources:
  SSMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-ssm.yaml"
      Parameters:
        Prefix: !Ref Prefix
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
        ValidHours: !Ref ValidHours
        WaitForSuccessTimeoutSeconds: !Ref WaitForSuccessTimeoutSeconds
        
  EventBridgeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-eventbridge.yaml"
      Parameters:
        Prefix: !Ref Prefix
        Runbook: !GetAtt SSMStack.Outputs.DeleteImageRunbook
        RunbookRoleArn: !GetAtt SSMStack.Outputs.DeleteImageRunbookRoleArn
