AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AZ:
    Type: String
    
  CidrBlock1:
    Type: String
    
  CidrBlock2:
    Type: String
    
  HTTPPort:
    Type: Number
    
  HTTPSPort:
    Type: Number
    
  iSCSIPort:
    Type: Number
    
  StorageGatewayPort1:
    Type: Number
    
  StorageGatewayPort2:
    Type: Number
    
  StorageGatewayPort3:
    Type: Number
    
  StorageGatewayPort4:
    Type: Number
    
  StorageGatewayPort5:
    Type: Number

  Prefix:
    Type: String
    
  VPCCidrBlock:
    Type: String
    

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCidrBlock
      EnableDnsHostnames: true
      EnableDnsSupport: true
      
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZ
      CidrBlock: !Ref CidrBlock1
      VpcId: !Ref VPC
      
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZ
      CidrBlock: !Ref CidrBlock2
      VpcId: !Ref VPC

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PrivateSubnetPrivateRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet
      RouteTableId: !Ref PrivateRouteTable
      
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${Prefix}-InstanceSecurityGroup"
      GroupDescription: Deny All.
      VpcId: !Ref VPC
        
  SSMEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${Prefix}-SSMEndpointSecurityGroup"
      GroupDescription: Allow HTTPS from InstanceSecurityGroup.
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref HTTPSPort
          ToPort: !Ref HTTPSPort
          SourceSecurityGroupId: !Ref InstanceSecurityGroup
          
  StorageGatewaySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${Prefix}-StorageGatewaySecurityGroup"
      GroupDescription: Allow Storage Gateway Traffic.
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref HTTPPort
          ToPort: !Ref HTTPPort
          SourceSecurityGroupId: !Ref InstanceSecurityGroup
        - IpProtocol: tcp
          FromPort: !Ref iSCSIPort
          ToPort: !Ref iSCSIPort
          SourceSecurityGroupId: !Ref InstanceSecurityGroup
          
  StorageGatewayEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${Prefix}-StorageGatewayEndpointSecurityGroup
      GroupDescription: Allow Storage Gateway Traffic.
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref HTTPSPort
          ToPort: !Ref HTTPSPort
          SourceSecurityGroupId: !Ref StorageGatewaySecurityGroup
        - IpProtocol: tcp
          FromPort: !Ref StorageGatewayPort1
          ToPort: !Ref StorageGatewayPort1
          SourceSecurityGroupId: !Ref StorageGatewaySecurityGroup
        - IpProtocol: tcp
          FromPort: !Ref StorageGatewayPort2
          ToPort: !Ref StorageGatewayPort2
          SourceSecurityGroupId: !Ref StorageGatewaySecurityGroup
        - IpProtocol: tcp
          FromPort: !Ref StorageGatewayPort3
          ToPort: !Ref StorageGatewayPort3
          SourceSecurityGroupId: !Ref StorageGatewaySecurityGroup
        - IpProtocol: tcp
          FromPort: !Ref StorageGatewayPort4
          ToPort: !Ref StorageGatewayPort4
          SourceSecurityGroupId: !Ref StorageGatewaySecurityGroup
        - IpProtocol: tcp
          FromPort: !Ref StorageGatewayPort5
          ToPort: !Ref StorageGatewayPort5
          SourceSecurityGroupId: !Ref StorageGatewaySecurityGroup
      
      
Outputs:
  VPC:
    Value: !Ref VPC
      
  PrivateSubnet:
    Value: !Ref PrivateSubnet
      
  PublicSubnet:
    Value: !Ref PublicSubnet
      
  PrivateRouteTable:
    Value: !Ref PrivateRouteTable
  
  InstanceSecurityGroup:
    Value: !Ref InstanceSecurityGroup
      
  SSMEndpointSecurityGroup:
    Value: !Ref SSMEndpointSecurityGroup
      
  StorageGatewaySecurityGroup:
    Value: !Ref StorageGatewaySecurityGroup
      
  StorageGatewayEndpointSecurityGroup:
    Value: !Ref StorageGatewayEndpointSecurityGroup
      
  AZ:
    Value: !Ref AZ
