AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AZ:
    Type: String
    
  EBSSize:
    Type: Number
    
  ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    
  InstanceType:
    Type: String
    
  Prefix:
    Type: String
    
  PrivateSubnet:
    Type: String
    
  StorageGatewaySecurityGroup:
    Type: String
    
    
Resources:
  StorageGatewayInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref PrivateSubnet
          GroupSet:
            - !Ref StorageGatewaySecurityGroup
            
  StorageGatewayInstanceEBS1:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: !Ref AZ
      Size: !Ref EBSSize
      VolumeType: gp3
      
  EBSAttachment1:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      Device: /dev/sdf
      InstanceId: !Ref StorageGatewayInstance
      VolumeId: !Ref StorageGatewayInstanceEBS1
      
  StorageGatewayInstanceEBS2:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: !Ref AZ
      Size: !Ref EBSSize
      VolumeType: gp3
      
  EBSAttachment2:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      Device: /dev/sdg
      InstanceId: !Ref StorageGatewayInstance
      VolumeId: !Ref StorageGatewayInstanceEBS2