AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Prefix:
    Type: String
    

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Ref Prefix
      #BucketEncryption:
      #  ServerSideEncryptionConfiguration:
      #    - BucketKeyEnabled: false
      #      ServerSideEncryptionByDefault: 
      #        #KMSMasterKeyID: String
      #        SSEAlgorithm: AES256


Outputs:
  #BucketName:
  #  Value: !Ref Bucket
  
  BucketArn:
    Value: !GetAtt Bucket.Arn