AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AdministrationRoleArn:
    Type: String

  ImageId:
    Type: String

  InstanceCapacity:
    Type: Number
    
  InstanceType:
    Type: String
    
  HTTPPort:
    Type: Number
    
  LambdaHandler:
    Type: String
    
  LambdaRuntime:
    Type: String
    
  Parameter1:
    Type: String
    
  Parameter2:
    Type: String
  
  Prefix:
    Type: String
    
  Region1:
    Type: String
    
  Region2:
    Type: String
    
  TemplateDir:
    Type: String
    
    
Resources:
  StackSet:
    Type: AWS::CloudFormation::StackSet
    Properties: 
      AdministrationRoleARN: !Ref AdministrationRoleArn
      Capabilities: 
        - CAPABILITY_IAM
      Parameters: 
        - ParameterKey: ImageId
          ParameterValue: !Ref ImageId
        - ParameterKey: InstanceCapacity
          ParameterValue: !Ref InstanceCapacity
        - ParameterKey: InstanceType
          ParameterValue: !Ref InstanceType
        - ParameterKey: HTTPPort
          ParameterValue: !Ref HTTPPort
        - ParameterKey: LambdaHandler
          ParameterValue: !Ref LambdaHandler
        - ParameterKey: LambdaRuntime
          ParameterValue: !Ref LambdaRuntime
        - ParameterKey: Prefix
          ParameterValue: !Ref Prefix
        - ParameterKey: SSMParameter
          ParameterValue: ""
        - ParameterKey: SSMParameterRegion
          ParameterValue: !Ref Region1
        - ParameterKey: TemplateDir
          ParameterValue: !Ref TemplateDir
      PermissionModel: SELF_MANAGED
      StackInstancesGroup: 
        - DeploymentTargets: 
            Accounts: 
              - !Ref AWS::AccountId
          ParameterOverrides: 
            - ParameterKey: SSMParameter
              ParameterValue: !Ref Parameter1
          Regions: 
            - !Ref Region1
        - DeploymentTargets: 
            Accounts: 
              - !Ref AWS::AccountId
          ParameterOverrides: 
            - ParameterKey: SSMParameter
              ParameterValue: !Ref Parameter2
          Regions: 
            - !Ref Region2
      StackSetName: !Sub "${Prefix}-stacksets"
      TemplateURL: !Sub "${TemplateDir}/${Prefix}-stacksets-template.yaml"
