AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ImageId:
    Type: String

  InstanceCapacity:
    Type: Number
    
  InstanceType:
    Type: String
    
  HTTPPort:
    Type: Number
    
  LambdaHandler:
    Type: String
    
  LambdaRuntime:
    Type: String
  
  Prefix:
    Type: String

  SSMParameter:
    Type: String
    
  SSMParameterRegion:
    Type: String
    
  TemplateDir:
    Type: String
    
    
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateDir}/${Prefix}-vpc.yaml"
      Parameters:
        AvailabilityZone1: a
        AvailabilityZone2: d
        CidrIp1: 10.0.1.0/24
        CidrIp2: 10.0.2.0/24
        CidrIp3: 10.0.3.0/24
        CidrIp4: 10.0.4.0/24
        HTTPPort: !Ref HTTPPort
        Prefix: !Ref Prefix
        VPCCidrBlock: 10.0.0.0/16
        
  EndpointStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
    Properties:
      TemplateURL: !Sub "${TemplateDir}/${Prefix}-endpoint.yaml"
      Parameters:
        Prefix: !Ref Prefix
        PrivateRouteTable: !GetAtt VPCStack.Outputs.PrivateRouteTable
        VPC: !GetAtt VPCStack.Outputs.VPC
        
  ELBStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
    Properties:
      TemplateURL: !Sub "${TemplateDir}/${Prefix}-elb.yaml"
      Parameters:
        ALBSecurityGroup: !GetAtt VPCStack.Outputs.ALBSecurityGroup
        HTTPPort: !Ref HTTPPort
        Prefix: !Ref Prefix
        PublicSubnet1: !GetAtt VPCStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2
        VPC: !GetAtt VPCStack.Outputs.VPC
        HealthyThresholdCount: 5
        HealthCheckTimeoutSeconds: 5
        HealthCheckIntervalSeconds: 30
        UnhealthyThresholdCount: 2
        HttpCode: 200
        
  AutoScalingStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - EndpointStack
      - ELBStack
    Properties:
      TemplateURL: !Sub "${TemplateDir}/${Prefix}-autoscaling.yaml"
      Parameters:
        ALBTargetGroup: !GetAtt ELBStack.Outputs.ALBTargetGroup
        DesiredCapacity: !Ref InstanceCapacity
        ImageId: !Ref ImageId
        InstanceSecurityGroup: !GetAtt VPCStack.Outputs.InstanceSecurityGroup
        InstanceType: !Ref InstanceType
        MaxSize: !Ref InstanceCapacity
        MinSize: !Ref InstanceCapacity
        Prefix: !Ref Prefix
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        
  CustomResourceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - ELBStack
    Properties:
      TemplateURL: !Sub "${TemplateDir}/${Prefix}-customresource.yaml"
      Parameters:
        ALBDNSName: !GetAtt ELBStack.Outputs.ALBDNSName
        Handler: !Ref LambdaHandler
        Prefix: !Ref Prefix
        Runtime: !Ref LambdaRuntime
        SSMParameter: !Ref SSMParameter
        SSMParameterRegion: !Ref SSMParameterRegion
