AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ALBDnsName:
    Type: String
    
  ALBHostedZoneId:
    Type: String
    
  DomainName1:
    Type: String
    
  DomainName2:
    Type: String
    
  HTTPSPort:
    Type: Number
    
  # domain1
  HostedZoneId1:
    Type: String
    
  # domain2
  HostedZoneId2:
    Type: String
    
  Prefix:
    Type: String
  

Resources:
  DnsHealthCheck:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Port: !Ref HTTPSPort
        Type: HTTPS
        ResourcePath: /
        FullyQualifiedDomainName: !Ref ALBDnsName
        RequestInterval: 30
        FailureThreshold: 3
        
  # domain1
  DnsRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId1
      Name: !Ref DomainName1
      Type: A
      AliasTarget: 
        DNSName: !Ref ALBDnsName
        HostedZoneId: !Ref ALBHostedZoneId
        
  # domain2
  DnsRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId2
      Name: !Ref DomainName2
      Type: A
      AliasTarget: 
        DNSName: !Ref ALBDnsName
        HostedZoneId: !Ref ALBHostedZoneId