AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AvailabilityZone1:
    Type: String
    
  AvailabilityZone2:
    Type: String
    
  CidrIp1:
    Type: String
    
  CidrIp2:
    Type: String
    
  #CidrIp3:
  #  Type: String
  #  
  #CidrIp4:
  #  Type: String
    
  HTTPSPort:
    Type: Number
    
  MySQLPort:
    Type: Number
    
  Prefix:
    Type: String

  VPCCidrBlock:
    Type: String
    
    
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCidrBlock
      EnableDnsHostnames: true
      EnableDnsSupport: true
      
  #PublicSubnet:
  #  Type: AWS::EC2::Subnet
  #  Properties:
  #    AvailabilityZone: !Sub "${AWS::Region}${AvailabilityZone1}"
  #    CidrBlock: !Ref CidrIp1
  #    VpcId: !Ref VPC
      
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}${AvailabilityZone1}"
      CidrBlock: !Ref CidrIp1
      VpcId: !Ref VPC
      
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}${AvailabilityZone2}"
      CidrBlock: !Ref CidrIp2
      VpcId: !Ref VPC
      
  #PrivateSubnet3:
  #  Type: AWS::EC2::Subnet
  #  Properties:
  #    AvailabilityZone: !Sub "${AWS::Region}${AvailabilityZone2}"
  #    CidrBlock: !Ref CidrIp4
  #    VpcId: !Ref VPC
      
  #IGW:
  #  Type: AWS::EC2::InternetGateway
#
  #IGWAttachment:
  #  Type: AWS::EC2::VPCGatewayAttachment
  #  Properties:
  #    VpcId: !Ref VPC
  #    InternetGatewayId: !Ref IGW
  #    
  #EIP:
  #  Type: AWS::EC2::EIP
  #  Properties:
  #    Domain: vpc
  #        
  #NATGateway:
  #  Type: AWS::EC2::NatGateway
  #  Properties:
  #    AllocationId: !GetAtt EIP.AllocationId
  #    SubnetId: !Ref PublicSubnet
  #    
  #PublicRouteTable:
  #  Type: AWS::EC2::RouteTable
  #  Properties:
  #    VpcId: !Ref VPC
#
  #RouteToInternet:
  #  Type: AWS::EC2::Route
  #  Properties:
  #    RouteTableId: !Ref PublicRouteTable
  #    DestinationCidrBlock: 0.0.0.0/0
  #    GatewayId: !Ref IGW
#
  #PublicSubnetPublicRouteTableAssociation:
  #  Type: AWS::EC2::SubnetRouteTableAssociation
  #  Properties:
  #    SubnetId: !Ref PublicSubnet
  #    RouteTableId: !Ref PublicRouteTable
      
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      
  #RouteToNATGateway:
  #  Type: AWS::EC2::Route
  #  Properties:
  #    RouteTableId: !Ref PrivateRouteTable
  #    DestinationCidrBlock: 0.0.0.0/0
  #    NatGatewayId: !Ref NATGateway
      
  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable
      

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${Prefix}-InstanceSecurityGroup"
      GroupDescription: Deny All.
      VpcId: !Ref VPC
      
  EndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${Prefix}-EndpointSecurityGroup"
      GroupDescription: Allow HTTPS from InstanceSecurityGroup.
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref HTTPSPort
          ToPort: !Ref HTTPSPort
          SourceSecurityGroupId: !Ref InstanceSecurityGroup
          
  RDSDenySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${Prefix}-RDSDenySecurityGroup"
      GroupDescription: Deny All.
      VpcId: !Ref VPC
      
  RDSAllowSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${Prefix}-RDSAllowSecurityGroup"
      GroupDescription: Allow MySQL.
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref MySQLPort
          ToPort: !Ref MySQLPort
          SourceSecurityGroupId: !Ref InstanceSecurityGroup
          

Outputs:
  #AvailabilityZone1:
  #  Value: !Ref AvailabilityZone1
  #  
  #AvailabilityZone2:
  #  Value: !Ref AvailabilityZone2
    
  PrivateSubnet1:
    Value: !Ref PrivateSubnet1
    
  PrivateSubnet2:
    Value: !Ref PrivateSubnet2
    
  #PrivateSubnet3:
  #  Value: !Ref PrivateSubnet3
  
  PrivateRouteTable:
    Value: !Ref PrivateRouteTable
    
  InstanceSecurityGroup:
    Value: !Ref InstanceSecurityGroup
    
  EndpointSecurityGroup:
    Value: !Ref EndpointSecurityGroup
    
  RDSDenySecurityGroup:
    Value: !Ref RDSDenySecurityGroup
    
  RDSAllowSecurityGroup:
    Value: !Ref RDSAllowSecurityGroup
    
  VPC:
    Value: !Ref VPC
    