AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Prefix:
    Type: String
    Default: soa-05-001
    
    
Resources:
  SSMEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - Fn::ImportValue: !Sub ${Prefix}-SSMEndpointSecurityGroup
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssm
      SubnetIds:
        - Fn::ImportValue: !Sub ${Prefix}-PrivateSubnet1
      VpcEndpointType: Interface
      VpcId:
        Fn::ImportValue: !Sub ${Prefix}-VPC

  EC2MessagesEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - Fn::ImportValue: !Sub ${Prefix}-SSMEndpointSecurityGroup
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ec2messages
      SubnetIds:
        - Fn::ImportValue: !Sub ${Prefix}-PrivateSubnet1
      VpcEndpointType: Interface
      VpcId:
        Fn::ImportValue: !Sub ${Prefix}-VPC
        
  SSMMessagesEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - Fn::ImportValue: !Sub ${Prefix}-SSMEndpointSecurityGroup
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssmmessages
      SubnetIds:
        - Fn::ImportValue: !Sub ${Prefix}-PrivateSubnet1
      VpcEndpointType: Interface
      VpcId:
        Fn::ImportValue: !Sub ${Prefix}-VPC
