AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Prefix:
    Type: String
    
  StorageClass:
    Type: String
    
  TransitionInDays:
    Type: Number
    

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Ref Prefix
      LifecycleConfiguration:
        Rules:
          - Id: !Sub "${Prefix}-Lifecyclerule"
            Status: Enabled
            Transitions: 
              - StorageClass: !Ref StorageClass
                TransitionInDays: !Ref TransitionInDays
