AWSTemplateFormatVersion: 2010-09-09

Parameters:
  TemplateBucketName:
    Type: String
    Default: [bucket-name]
    
  Prefix:
    Type: String
    Default: soa-06-001

  StorageClass:
    Type: String
    Default: INTELLIGENT_TIERING
    
  TransitionInDays:
    Type: Number
    Default: 1
    
    
Resources:
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-s3.yaml"
      Parameters:
        Prefix: !Ref Prefix
        StorageClass: !Ref StorageClass
        TransitionInDays: !Ref TransitionInDays
