AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AvailabilityZone:
    Type: String
    
  DBAllocatedStorage:
    Type: Number
    
  DBEngine:
    Type: String
    
  DBEngineVersion:
    Type: String
    
  DBInstanceClass:
    Type: String

  DBMasterUsername:
    Type: String
    
  DBMasterUserPassword:
    Type: String
    
  DBSecurityGroup:
    Type: String
    
  DBSubnet1:
    Type: String
    
  DBSubnet2:
    Type: String

  Prefix:
    Type: String
    

Resources:
  DBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      AllocatedStorage: !Ref DBAllocatedStorage
      AvailabilityZone: !Sub "${AWS::Region}${AvailabilityZone}"
      DBInstanceClass: !Ref DBInstanceClass
      DBInstanceIdentifier: !Ref Prefix
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: !Ref DBEngine
      EngineVersion: !Ref DBEngineVersion
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: !Ref DBMasterUserPassword
      StorageEncrypted: false
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
        
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: dbsubnetgroup
      DBSubnetGroupDescription: testgroup.
      SubnetIds:
        - !Ref DBSubnet1
        - !Ref DBSubnet2


Outputs:
  DBInstanceArn:
    Value: !GetAtt DBInstance.DBInstanceArn
    
  DBSubnetGroup:
    Value: !Ref DBSubnetGroup
