AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DomainName1:
    Type: String
    
  DomainName2:
    Type: String
    
  # awstut.net
  HostedZoneId1:
    Type: String
    
  # awstut.link
  HostedZoneId2:
    Type: String
    
  Prefix:
    Type: String


Resources:
  # awstut.net
  Certificate1:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName1
      DomainValidationOptions:
        - DomainName: !Ref DomainName1
          HostedZoneId: !Ref HostedZoneId1
      ValidationMethod: DNS
      
  # awstut.link
  Certificate2:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName2
      DomainValidationOptions:
        - DomainName: !Ref DomainName2
          HostedZoneId: !Ref HostedZoneId2
      ValidationMethod: DNS


Outputs:
  Certificate1:
    Value: !Ref Certificate1
    Export:
      Name: !Sub ${Prefix}-Certificate1
      
  Certificate2:
    Value: !Ref Certificate2
    Export:
      Name: !Sub ${Prefix}-Certificate2
