AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Limit:
    Type: Number

  Prefix:
    Type: String
    
    
Resources:
  RuleGroup:
    Type: AWS::WAFv2::RuleGroup
    Properties:
      Capacity: 10
      Name: !Sub "${Prefix}-RateRestrictionRuleGroup"
      Rules:
        - Action:
            Block: {}
          Name: !Sub "${Prefix}-RateRestrictionRule"
          Priority: 0
          Statement:
            #GeoMatchStatement:
            #  CountryCodes:
            #    - JP
            RateBasedStatement:
              AggregateKeyType: IP
              Limit: !Ref Limit
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: !Sub "${Prefix}-RateRestrictionRule"
            SampledRequestsEnabled: true
      Scope: CLOUDFRONT
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: !Sub "${Prefix}-RateRestrictionRuleGroup"
        SampledRequestsEnabled: true

  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      DefaultAction:
        Allow: {}
      Name: !Sub "${Prefix}-WebACL"
      Rules:
        - Name: !Sub "${Prefix}-WebACL-RateRestriction"
          OverrideAction:
            None: {}
          Priority: 0
          Statement:
            RuleGroupReferenceStatement:
              Arn: !GetAtt RuleGroup.Arn
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: !Sub "${Prefix}-WebACL-RateRestriction"
            SampledRequestsEnabled: true
      Scope: CLOUDFRONT
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: !Ref Prefix
        SampledRequestsEnabled: true
        
  #WebACLAssociation:
  #  Type: AWS::WAFv2::WebACLAssociation
  #  Properties: 
  #    ResourceArn: !Ref ALBArn
  #    WebACLArn: !GetAtt WebACL.Arn
  
  
Outputs:
  WebACLArn:
    Value: !GetAtt WebACL.Arn